### ISSUE TITLE
java.lang.UnsupportedOperationException generated when run with Java 9 (but not Java 8)

### ISSUE THREAD

**Issue by rmbarnett-rice** [OpenHFT/Java-Runtime-Compiler#27]
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.openhft.compiler.CompilerUtils (file:/home/ubuntu/master/tool_files/floodgage/floodgage-1.0.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of net.openhft.compiler.CompilerUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsupportedOperationException
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at net.openhft.compiler.CachedCompiler.compileFromJava(CachedCompiler.java:101)
	at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:143)
	at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:70)
	at edu.rice.cs.caper.floodgage.application.floodgage.TrailsRunner.runTrails(TrailsRunner.java:73)
	at edu.rice.cs.caper.floodgage.application.floodgage.FloodGage.run(FloodGage.java:63)
	at edu.rice.cs.caper.floodgage.application.floodgage.FloodGageMain.main(FloodGageMain.java:39)
Caused by: java.lang.UnsupportedOperationException
	at java.compiler@9.0.1/javax.tools.JavaFileManager.listLocationsForModules(JavaFileManager.java:566)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.listLocationsForModules(ClientCodeWrapper.java:397)
	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder$ModuleLocationIterator.hasNext(ModuleFinder.java:135)
	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.scanModulePath(ModuleFinder.java:288)
	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findAllModules(ModuleFinder.java:184)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.getUnnamedModuleCompleter(Modules.java:1396)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:466)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:270)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:236)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initModules(JavaCompiler.java:1031)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:925)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
```

```
$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

**Comment by epickrram** [comment]
Hi,
thanks for the report. While Java9 compatibility is progressing for most of the OpenHFT libraries, there are still a few areas where more work is needed. I'm afraid you've encountered one of them.

We are aware of this issue, and it will be addressed in due course.
