### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool

### ISSUE THREAD

**Issue by matyklugDebbuged** [OpenHFT/Java-Runtime-Compiler#44]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.AssertionError: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
	at net.openhft.compiler.CompilerUtils.reset(CompilerUtils.java:85)
	at net.openhft.compiler.CompilerUtils.<clinit>(CompilerUtils.java:69)
	at tests.javacompile.Main.main(Main.java:22)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.openhft.compiler.CompilerUtils.reset(CompilerUtils.java:81)
	... 2 more

**Comment by RobAustin** [comment]
Which version of java are you using. Check you have tools.jar on the class path ?

**Comment by matyklugDebbuged** [comment]
java 8. and where should i get tools.jar?

**Comment by RobAustin** [comment]
its in the JDK, on my mac

/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/lib/tools.jar

![image](https://user-images.githubusercontent.com/6506056/66267667-cc47b500-e82b-11e9-9425-1343f56e214a.png)

**Comment by kannankalli** [comment]
HI, 
We are migrating our application to JRE 11 from JRE 8. we are using 3.23.5 version of chronicle map. Application is shutting down while starting. Below is the error 


Exception in thread "main" java.lang.AssertionError: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
at net.openhft.compiler.CompilerUtils.reset(CompilerUtils.java:64)

Based on my understanding, tools.jar is not present any more in jre 11.  But chorincle map depends on JAvacTool which is from tools.jar. How should we mitigate this problem ? 
Should i add tools.jar as part of the classpath in JRE 11  ( copied from JRE 8 ) ?
