### ISSUE TITLE
RuntimeCompileTest not configured for Java 11+

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Java-Runtime-Compiler#76]
on Azul Zing and Java 17 builds e.g.
```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Unable to invoke method listLocationsForModules
  at mytest.RuntimeCompileTest.testMultiThread(RuntimeCompileTest.java:85)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Unable to invoke method listLocationsForModules
  at mytest.RuntimeCompileTest.lambda$testMultiThread$0(RuntimeCompileTest.java:79)
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Unable to invoke method listLocationsForModules
  at mytest.RuntimeCompileTest.lambda$testMultiThread$0(RuntimeCompileTest.java:75)
Caused by: java.lang.UnsupportedOperationException: Unable to invoke method listLocationsForModules
  at mytest.RuntimeCompileTest.lambda$testMultiThread$0(RuntimeCompileTest.java:75)
Caused by: java.lang.reflect.InvocationTargetException
  at mytest.RuntimeCompileTest.lambda$testMultiThread$0(RuntimeCompileTest.java:75)
Caused by: java.util.ConcurrentModificationException
  at mytest.RuntimeCompileTest.lambda$testMultiThread$0(RuntimeCompileTest.java:75)
------- Stderr: -------
Fatal Error: Unable to find package java.lang in classpath or bootclasspath
```

**Comment by peter-lawrey** [comment]
The Fatal Error doesn't appear to be an error from our code.
