### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Java-Runtime-Compiler#85]

**Comment by minborg** [comment]
Run under Java 11 locally:
```
[INFO] Running mytest.RuntimeCompileTest
nThreads = 16
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.858 s <<< FAILURE! - in mytest.RuntimeCompileTest
[ERROR] mytest.RuntimeCompileTest.testMultiThread  Time elapsed: 0.784 s  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Unable to invoke method listLocationsForModules
	at mytest.RuntimeCompileTest.testMultiThread(RuntimeCompileTest.java:88)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Unable to invoke method listLocationsForModules
	at mytest.RuntimeCompileTest.lambda$testMultiThread$0(RuntimeCompileTest.java:82)
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Unable to invoke method listLocationsForModules
	at mytest.RuntimeCompileTest.lambda$testMultiThread$0(RuntimeCompileTest.java:78)
Caused by: java.lang.UnsupportedOperationException: Unable to invoke method listLocationsForModules
	at mytest.RuntimeCompileTest.lambda$testMultiThread$0(RuntimeCompileTest.java:78)
Caused by: java.lang.reflect.InvocationTargetException
	at mytest.RuntimeCompileTest.lambda$testMultiThread$0(RuntimeCompileTest.java:78)
Caused by: java.util.ConcurrentModificationException
	at mytest.RuntimeCompileTest.lambda$testMultiThread$0(RuntimeCompileTest.java:78)

```

**Comment by minborg** [comment]
Apparently, some implementations of `listLocationsForModules()` are not thread-safe.
